services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - 'php-fpm'
    volumes:
      - './:/app'
      - './.docker/nginx:/etc/nginx/conf.d'
      - './.docker/log/nginx:/var/log/nginx'
      - './.docker/ssl:/etc/nginx/ssl'
    networks:
      - 'my_network'
  php-fpm:
    user: '1000'
    build:
      context: './.docker/php'
      dockerfile: './Dockerfile'
      args:
        APP_ENV: '${APP_ENV}'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - 'mysql'
      - 'memcached'
    volumes:
      - './:/app'
      - './.docker/php/custom-php.ini:/usr/local/etc/php/php.ini'
      - './.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    networks:
      - 'my_network'
  memcached:
    image: 'memcached:latest'
    ports:
      - '11211:11211'
    networks:
      - 'my_network'

  mysql:
    image: 'mysql:latest'
    restart: 'always'
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - './.docker/mysql/my.cnf:/etc/mysql/my.cnf'
      - 'mysqldata:/var/lib/mysql'
    networks:
      - 'my_network'
volumes:
  mysqldata:

networks:
  my_network:
    driver: bridge